### ISSUE TITLE
Unable to download connector from Confluent website

### ISSUE THREAD

**Issue by henryjw** [thomaskwscott/kafka-connect-http#2]
Not sure if this should be reported here or on Confluent's site, but I'm unable to download the plugin. I've tried both downloading it from the website and installing it via the CLI. 
Is there a way to build / compile it from source?

CLI: 

```
root@2c54e63375cd:/# confluent-hub install thomaskwscott/kafka-connect-http:latest


The component can be installed in any of the following Confluent Platform installations:
  1. / (installed rpm/deb package) 
  2. / (where this tool is installed) 
Choose one of these to continue the installation (1-2): 2
Do you want to install this into /usr/share/confluent-hub-components? (yN) y

Unable to find a component 
 
Error: Component not found, specify either valid name from Confluent Hub in format: <owner>/<name>:<version:latest> or path to a local file
```

Website: 
<img width="1131" alt="http connector download error" src="https://user-images.githubusercontent.com/3443648/62303537-4fbee180-b44a-11e9-85bd-074fe6b88721.png">

**Comment by ghost** [comment]
This is caused by Confluent, not the author of this connector.  They have taken the decision to replace open source community connectors with commercial ones written by Confluent on their Confluent Hub.

I have a [separate PR](https://github.com/thomaskwscott/kafka-connect-http/pull/3) in that fixes the build for this package, which will allow you to build it yourself with `mvn package`.

**Comment by sgerrand** [comment]
Hooray for Confluent. Thanks, @WheresAlice. 💝

**Comment by henryjw** [comment]
Thanks @WheresAlice.
